# Generated by Django 5.2.5 on 2025-08-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='publicites/')),
                ('lien', models.URLField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produitmarche',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marche/'),
        ),
    ]
