# Generated by Django 5.1.7 on 2025-08-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publicite_alter_produitmarche_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publicites/'),
        ),
    ]
