# Generated by Django 5.1.7 on 2025-08-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_publicite_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_type', models.CharField(max_length=50)),
                ('produit_id', models.PositiveIntegerField()),
                ('nom_produit', models.CharField(max_length=100)),
                ('prix_unitaire', models.PositiveIntegerField()),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.commande')),
            ],
        ),
    ]
